version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    # เสิร์ฟด้วย vite preview 4173 → map ออกเป็น 3000 เพื่อจำง่าย
    ports:
      - "3000:4173"
